from app.agent.prompts.templates import (
    MATCH_SCORER_PROMPT,
    ATS_AUDITOR_PROMPT,
    CV_REWRITER_PROMPT,
    COVER_LETTER_PROMPT,
    INTERVIEW_SIMULATOR_PROMPT,
)

__all__ = [
    "MATCH_SCORER_PROMPT",
    "ATS_AUDITOR_PROMPT",
    "CV_REWRITER_PROMPT",
    "COVER_LETTER_PROMPT",
    "INTERVIEW_SIMULATOR_PROMPT",
]
